spring.application.name=AlumniManagementSystem

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000

# Database Configuration
spring.datasource.url=JDBC:mysql://localhost:3306/alumni_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.AlumniManagementSystem=DEBUG
logging.level.org.springframework.security=DEBUG

# ==================== EMAIL CONFIG ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=birajdarganu96@gmail.com

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# ==================== SUPER ADMIN SEED ====================
app.super-admin.email=ganesh@alumnihub.com
app.super-admin.password=Admin@123
app.super-admin.first-name=Super
app.super-admin.last-name=Admin
app.super-admin.phone=+919637310381